package dmacc.beans;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;

//@Embeddable - would have to autowire to Customer
@Entity
public class CustomerReservation {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private long id;

	// This is generated by the programming based upon seats available/flight
	// capacity: Example 1A
	private String seatIdentifierText;

	@ManyToOne
	@JoinColumn(name = "flightId")
	private Flight flight;

	@OneToOne
	@JoinColumn(name = "custId")
	private Customer customer;

	// constructors
	public CustomerReservation() {
	}

	public CustomerReservation(String seatIdentifierText, Flight flight, Customer customer) {
		super();
		this.seatIdentifierText = seatIdentifierText;
		this.flight = flight;
		this.customer = customer;
	}

	public long getId() {
		return id;
	}

	public String getSeatIdentifierText() {
		return seatIdentifierText;
	}

	public void setSeatIdentifierText(String seatIdentifierText) {
		this.seatIdentifierText = seatIdentifierText;
	}

	public Flight getFlight() {
		return flight;
	}

	public void setFlight(Flight flight) {
		this.flight = flight;
	}

	public Customer getCustomer() {
		return customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Override
	public String toString() {
		return "CustomerReservation [id=" + id + ", seatIdentifierText=" + seatIdentifierText + ", flight=" + flight
				+ ", customer=" + customer + "]";
	}

}
